# Generated by Django 4.2.7 on 2023-11-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_country_manufacturer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
